// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"components/index":{"id":"components/index","path":"components","parentId":"DocLayout","meta":{"_atom_route":true}},"components/UseCopyToClipboard/index":{"id":"components/UseCopyToClipboard/index","path":"components/use-copy-to-clipboard","parentId":"DocLayout","meta":{"_atom_route":true}},"components/UseCounter/index":{"id":"components/UseCounter/index","path":"components/use-counter","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'components/index': React.lazy(() => import(/* webpackChunkName: "index.md" */'/Users/long.xiao/Documents/Github/hooks/src/index.md')),
'components/UseCopyToClipboard/index': React.lazy(() => import(/* webpackChunkName: "UseCopyToClipboard__index.md" */'/Users/long.xiao/Documents/Github/hooks/src/UseCopyToClipboard/index.md')),
'components/UseCounter/index': React.lazy(() => import(/* webpackChunkName: "UseCounter__index.md" */'/Users/long.xiao/Documents/Github/hooks/src/UseCounter/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
