// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/long.xiao/Documents/Github/hooks/node_modules/.pnpm/registry.npmmirror.com+dumi@2.2.1_6rzba2rxqjc2dw36rowdiq7pwq/node_modules/dumi/theme-default/slots/Footer/index.js';
