// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/long.xiao/Documents/Github/hooks/node_modules/.pnpm/registry.npmmirror.com+dumi@2.2.1_@babel+core@7.22.9_@types+node@17.0.45_@types+react@18.0.15_kx2hpg3w7e5wo3sg7mngpc3tya/node_modules/dumi/theme-default/slots/Header/index.js';
